name: Run Insomnia API Tests (Inso CLI)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-insomnia-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Inso CLI
        uses: kong/setup-inso@v2
        with:
          inso-version: '10.3.1'

      - name: Create report folder
        run: mkdir -p reports

      - name: Run Insomnia tests
        id: inso_test
        run: |
          set -o pipefail
          inso run test --workspace ./insomnia/Insomnia_2025-11-05.yaml --ci --verbose | tee reports/inso-output.log

      - name: Upload Inso CLI log
        uses: actions/upload-artifact@v4
        with:
          name: inso-run-logs
          path: reports/inso-output.log
