name: Run Insomnia API Tests (Inso CLI)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-insomnia-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install libcurl dev
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev

      - name: Install Inso CLI
        run: npm install -g insomnia-inso@3.6.0

      - name: Create reports folder
        run: mkdir -p reports

      - name: Run Insomnia tests
        id: inso_test
        run: |
          set -o pipefail
          inso run test --workspace ./insomnia/Insomnia_2025-11-05.yaml --ci --verbose | tee reports/inso-output.log
          export INSOTEST_EXIT_CODE=${PIPESTATUS[0]}
          exit $INSOTEST_EXIT_CODE

      - name: Upload Inso CLI log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: inso-run-logs
          path: reports/inso-output.log
